package com.incoteam.realsaathi.utils

data class CountryCode(val name: String, val dialCode: String, val iso: String)

object CountryCodes {
    val all = listOf(
        CountryCode("India", "+91", "IN"), CountryCode("United States", "+1", "US"), CountryCode("Canada", "+1", "CA"), CountryCode("United Kingdom", "+44", "GB"), CountryCode("Australia", "+61", "AU"), CountryCode("New Zealand", "+64", "NZ"), CountryCode("United Arab Emirates", "+971", "AE"), CountryCode("Saudi Arabia", "+966", "SA"), CountryCode("Qatar", "+974", "QA"), CountryCode("Kuwait", "+965", "KW"), CountryCode("Singapore", "+65", "SG"), CountryCode("Malaysia", "+60", "MY"), CountryCode("Bangladesh", "+880", "BD"), CountryCode("Pakistan", "+92", "PK"), CountryCode("Sri Lanka", "+94", "LK"), CountryCode("Nepal", "+977", "NP"), CountryCode("Afghanistan", "+93", "AF"), CountryCode("China", "+86", "CN"), CountryCode("Japan", "+81", "JP"), CountryCode("South Korea", "+82", "KR"), CountryCode("Indonesia", "+62", "ID"), CountryCode("Thailand", "+66", "TH"), CountryCode("Philippines", "+63", "PH"), CountryCode("Vietnam", "+84", "VN"), CountryCode("Germany", "+49", "DE"), CountryCode("France", "+33", "FR"), CountryCode("Italy", "+39", "IT"), CountryCode("Spain", "+34", "ES"), CountryCode("Netherlands", "+31", "NL"), CountryCode("Ireland", "+353", "IE"), CountryCode("Portugal", "+351", "PT"), CountryCode("Switzerland", "+41", "CH"), CountryCode("Sweden", "+46", "SE"), CountryCode("Norway", "+47", "NO"), CountryCode("Denmark", "+45", "DK"), CountryCode("Belgium", "+32", "BE"), CountryCode("Austria", "+43", "AT"), CountryCode("South Africa", "+27", "ZA"), CountryCode("Nigeria", "+234", "NG"), CountryCode("Kenya", "+254", "KE"), CountryCode("Egypt", "+20", "EG"), CountryCode("Turkey", "+90", "TR"), CountryCode("Russia", "+7", "RU"), CountryCode("Ukraine", "+380", "UA"), CountryCode("Brazil", "+55", "BR"), CountryCode("Mexico", "+52", "MX"), CountryCode("Argentina", "+54", "AR"), CountryCode("Chile", "+56", "CL"), CountryCode("Colombia", "+57", "CO")
    )
}
