import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import StatusBadge from './StatusBadge'

const scopes = ['users', 'wallet', 'moderation', 'kyc', 'banners', 'support', 'audit']
export default function CoWorkerPage() {
  const [members, setMembers] = useState([]); const [email, setEmail] = useState(''); const [userId, setUserId] = useState(''); const [permissions, setPermissions] = useState(['users']); const [editing, setEditing] = useState(null); const [error, setError] = useState('')
  const load = async () => { const result = await supabase.from('admin_members').select('id,email,user_id,permissions,status,created_at').order('created_at', { ascending: false }); if (result.error) setError(result.error.message); else setMembers(result.data || []) }
  useEffect(() => { load() }, [])
  const toggle = (scope, setter) => setter(current => current.includes(scope) ? current.filter(item => item !== scope) : [...current, scope])
  const add = async event => { event.preventDefault(); setError(''); const result = await supabase.from('admin_members').insert({ email, user_id: userId, permissions }); if (result.error) setError(result.error.message); else { setEmail(''); setUserId(''); setPermissions(['users']); await load() } }
  const save = async member => { const result = await supabase.from('admin_members').update({ permissions: editing.permissions }).eq('id', member.id); if (result.error) setError(result.error.message); else { await supabase.rpc('admin_record_audit', { p_action: 'admin_permissions_changed', p_entity_type: 'admin_member', p_entity_id: member.id, p_metadata: { permissions: editing.permissions } }); setEditing(null); await load() } }
  const remove = async member => { if (!window.confirm(`Revoke admin access for ${member.email}?`)) return; const result = await supabase.from('admin_members').delete().eq('id', member.id); if (result.error) setError(result.error.message); else { await supabase.rpc('admin_record_audit', { p_action: 'admin_access_revoked', p_entity_type: 'admin_member', p_entity_id: member.id, p_metadata: { email: member.email } }); await load() } }
  return <><div className="section-title"><div><h2>Co-workers</h2><p>Super-admin controlled access</p></div></div><div className="overview-grid"><form className="panel worker-form" onSubmit={add}><h3>Add access member</h3><p className="muted">Create the Auth account separately, then assign its user UUID here.</p><input required type="email" placeholder="work email" value={email} onChange={e => setEmail(e.target.value)} /><input required placeholder="Auth user UUID" value={userId} onChange={e => setUserId(e.target.value)} /><div className="scope-list">{scopes.map(scope => <label key={scope}><input type="checkbox" checked={permissions.includes(scope)} onChange={() => toggle(scope, setPermissions)} />{scope}</label>)}</div>{error && <div className="error">{error}</div>}<button className="primary-btn">Grant scoped access</button></form><div className="panel table-wrap"><table className="table"><thead><tr><th>Email</th><th>Scopes</th><th>Status</th><th>Actions</th></tr></thead><tbody>{members.map(member => <tr key={member.id}><td>{member.email}</td><td>{editing?.id === member.id ? <div className="scope-list">{scopes.map(scope => <label key={scope}><input type="checkbox" checked={editing.permissions.includes(scope)} onChange={() => toggle(scope, value => setEditing({ ...editing, permissions: value }))} />{scope}</label>)}</div> : (member.permissions || []).join(', ')}</td><td><StatusBadge value={member.status} /></td><td className="row-actions">{editing?.id === member.id ? <><button className="mini-btn" onClick={() => save(member)}>Save</button><button className="mini-btn" onClick={() => setEditing(null)}>Cancel</button></> : <><button className="mini-btn" onClick={() => setEditing({ ...member, permissions: member.permissions || [] })}>Edit</button><button className="mini-btn danger-btn" onClick={() => remove(member)}>Remove</button></>}</td></tr>)}</tbody></table></div></div></>
}
