import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import StatusBadge from './StatusBadge'

export default function KycReviewPage() {
  const [rows, setRows] = useState([]); const [selected, setSelected] = useState(null); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const load = useCallback(async () => { const result = await supabase.from('host_kyc_details').select('*').order('created_at', { ascending: false }).limit(100); if (result.error) setError(result.error.message); else setRows(result.data || []) }, [])
  useEffect(() => { load() }, [load])
  const review = async status => { if (!selected || !window.confirm(`${status === 'approved' ? 'Approve' : 'Reject'} this KYC?`)) return; const kyc = await supabase.from('host_kyc_details').update({ status, message, review_message: message, reviewed_at: new Date().toISOString() }).eq('user_id', selected.user_id); if (kyc.error) return setError(kyc.error.message); const user = await supabase.from('users').update({ host_status: status }).eq('id', selected.user_id); if (user.error) return setError(user.error.message); setSelected(null); setMessage(''); await load() }
  return <><div className="section-title"><div><h2>KYC review</h2><p>Host verification queue · sensitive documents</p></div><button className="ghost-btn" onClick={load}>Refresh</button></div><div className="panel"><div className="table-wrap"><table className="table"><thead><tr><th>Host ID</th><th>Name</th><th>Email</th><th>Status</th><th>Submitted</th></tr></thead><tbody>{rows.map(row => <tr className="clickable-row" key={row.user_id} onClick={() => { setSelected(row); setMessage(row.review_message || row.message || '') }}><td>{row.user_id}</td><td>{row.full_name}</td><td>{row.email_address}</td><td><StatusBadge value={row.status} /></td><td>{new Date(row.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div></div>{selected && <div className="inspector panel"><div className="section-title"><div><h2>{selected.full_name}</h2><p>Host KYC / {selected.user_id}</p></div><button className="ghost-btn" onClick={() => setSelected(null)}>Close</button></div><div className="detail-grid"><span>Aadhaar<strong>{selected.aadhaar_masked}</strong></span><span>PAN<strong>{selected.pan_masked}</strong></span><span>Bank<strong>{selected.bank_name} · {selected.bank_account_masked}</strong></span><span>IFSC<strong>{selected.ifsc_code}</strong></span><span>Phone<strong>{selected.phone_number}</strong></span><span>DOB<strong>{selected.date_of_birth}</strong></span></div><div className="kyc-images">{[selected.aadhaar_image_data, selected.pan_image_data, selected.selfie_aadhaar_image_data].filter(Boolean).map((image, index) => <img key={index} src={image} alt={`KYC document ${index + 1}`} />)}</div><textarea className="review-message" placeholder="Review message" value={message} onChange={e => setMessage(e.target.value)} /><div className="row-actions"><button className="primary-btn" onClick={() => review('approved')}>Approve KYC</button><button className="mini-btn danger-btn" onClick={() => review('rejected')}>Reject KYC</button></div>{error && <div className="error">{error}</div>}</div>}</>
}
