import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import StatusBadge from './StatusBadge'

const queues = [
  { key: 'user_reports', label: 'Reports', columns: 'id,reporter_id,reported_id,reason,context,note,status,admin_note,created_at,resolved_at' },
  { key: 'feedback_messages', label: 'Feedback', columns: 'id,user_id,role,category,body,status,admin_note,created_at' },
]

export default function ModerationPage() {
  const [queue, setQueue] = useState(queues[0]); const [rows, setRows] = useState([])
  const [selected, setSelected] = useState(null); const [note, setNote] = useState(''); const [error, setError] = useState('')
  const load = useCallback(async () => { const result = await supabase.from(queue.key).select(queue.columns).order('created_at', { ascending: false }).limit(100); if (result.error) return setError(result.error.message); let next = result.data || []; if (queue.key === 'user_reports') { const ids = [...new Set(next.flatMap(row => [row.reporter_id, row.reported_id]).filter(Boolean))]; const people = ids.length ? await supabase.from('users').select('id,public_id,username,role,device_id,device_brand,account_status').in('id', ids) : { data: [], error: null }; if (people.error) return setError(people.error.message); const byId = Object.fromEntries((people.data || []).map(person => [person.id, person])); next = next.map(row => ({ ...row, reporter: byId[row.reporter_id], reported: byId[row.reported_id] })) } setError(''); setRows(next) }, [queue])
  useEffect(() => { setSelected(null); load() }, [load])
  const updateStatus = async status => { if (!selected || !window.confirm(`Mark this item ${status}?`)) return; const values = queue.key === 'feedback_messages' ? { status, admin_note: note, updated_at: new Date().toISOString() } : { status, admin_note: note, ...(status === 'resolved' || status === 'closed' ? { resolved_at: new Date().toISOString() } : {}) }; const result = await supabase.from(queue.key).update(values).eq('id', selected.id); if (result.error) setError(result.error.message); else { await supabase.rpc('admin_record_audit', { p_action: 'moderation_status_changed', p_entity_type: queue.key, p_entity_id: selected.id, p_metadata: { status, note } }); setSelected(null); setNote(''); await load() } }
  const ban = async (device = false) => { if (!selected?.reported?.id || !window.confirm(device ? 'Ban this device and account?' : 'Ban this account?')) return; const rpc = device ? 'admin_ban_device' : 'admin_ban_user'; const args = device ? { p_device_id: selected.reported.device_id, p_user_id: selected.reported.id, p_report_id: selected.id, p_reason: selected.reason, p_brand: selected.reported.device_brand || '' } : { p_user_id: selected.reported.id, p_reason: selected.reason }; if (device && !selected.reported.device_id) return setError('No device ID is stored for this account.'); const result = await supabase.rpc(rpc, args); if (result.error) setError(result.error.message); else { await supabase.rpc('admin_record_audit', { p_action: device ? 'device_banned' : 'user_banned', p_entity_type: 'user', p_entity_id: selected.reported.id, p_metadata: { reportId: selected.id, reason: selected.reason } }); setSelected({ ...selected, reported: { ...selected.reported, account_status: 'banned' } }); await load() } }
  return <><div className="section-title"><div><h2>Moderation</h2><p>Reports and feedback submitted from client and host apps</p></div><button className="ghost-btn" onClick={load}>Refresh</button></div><div className="toolbar">{queues.map(item => <button className={queue.key === item.key ? 'primary-btn' : 'ghost-btn'} onClick={() => setQueue(item)} key={item.key}>{item.label}</button>)}</div>{error && <div className="error">{error}</div>}<div className="panel table-wrap"><table className="table"><thead><tr><th>Created</th><th>Type</th><th>Reporter</th><th>Reported profile</th><th>Status</th></tr></thead><tbody>{rows.map(row => <tr className="clickable-row" key={row.id} onClick={() => { setSelected(row); setNote(row.admin_note || '') }}><td>{new Date(row.created_at).toLocaleString()}</td><td>{row.category || row.reason || row.context}</td><td>{row.reporter?.username || row.reporter_id || row.role}</td><td>{row.reported?.username || row.reported?.public_id || row.reported_id || 'App issue'}</td><td><StatusBadge value={row.status} /></td></tr>)}</tbody></table>{!rows.length && <div className="empty">No moderation items found.</div>}</div>{selected && <div className="inspector panel"><div className="section-title"><div><h2>Review item</h2><p>{selected.id}</p></div><button className="ghost-btn" onClick={() => setSelected(null)}>Close</button></div><p className="muted">{selected.body || selected.note || `${selected.reason || 'Report'} · ${selected.context || ''}`}</p>{selected.reported && <div className="detail-grid"><span>Reporter<strong>{selected.reporter?.username || selected.reporter_id}</strong></span><span>Reported<strong>{selected.reported.username || selected.reported.public_id || selected.reported.id}</strong></span><span>Device<strong>{selected.reported.device_brand || 'Unknown'} · {selected.reported.device_id ? 'Available' : 'Missing'}</strong></span><span>Account<strong>{selected.reported.account_status || 'active'}</strong></span></div>}{(queue.key === 'feedback_messages' || queue.key === 'user_reports') && <textarea className="review-message" placeholder="Internal admin note" value={note} onChange={event => setNote(event.target.value)} /> }<div className="row-actions"><button className="mini-btn" onClick={() => updateStatus('in_review')}>In review</button><button className="primary-btn" onClick={() => updateStatus('resolved')}>Resolve</button><button className="mini-btn" onClick={() => updateStatus('closed')}>Close case</button>{selected.reported && <><button className="mini-btn danger-btn" onClick={() => ban(false)}>Ban ID</button><button className="mini-btn danger-btn" disabled={!selected.reported.device_id} onClick={() => ban(true)}>Ban device</button></>}</div></div>}</>
}
