import { useDashboardMetrics } from '../hooks/useDashboardMetrics'
import MetricCard from './MetricCard'
import StatusBadge from './StatusBadge'
import DashboardTrend from './DashboardTrend'

export default function OverviewPage({ permissions }) {
  const data = useDashboardMetrics(permissions)
  const money = value => `₹${Number(value || 0).toLocaleString('en-IN')}`
  return <><div className="page-actions"><div><p className="eyebrow">Overview</p><h2 className="page-heading">Dashboard</h2><p className="muted">A quick view of accounts, calls, wallet activity, and support.</p></div><button className="ghost-btn" onClick={data.reload}>Refresh data</button></div>{data.error && <div className="error">Some panels are unavailable: {data.error}</div>}<div className="metric-grid"><MetricCard label="Total users" value={data.loading ? '—' : data.users.toLocaleString()} note={`${data.active.toLocaleString()} active accounts`} /><MetricCard label="Hosts" value={data.loading ? '—' : data.hosts.toLocaleString()} note="Registered host accounts" /><MetricCard label="Calls" value={data.loading ? '—' : data.calls.toLocaleString()} note={`${data.minutes.toLocaleString()} minutes tracked`} /><MetricCard label="Recharge revenue" value={data.loading ? '—' : money(data.rechargeAmount)} note={`${data.rechargeUsers} paying users`} /></div><div className="metric-grid metric-grid-small"><MetricCard label="Answered" value={data.answered} note="Completed call events" /><MetricCard label="Missed / cancelled" value={data.missed + data.cancelled} note={`${data.missed} missed · ${data.cancelled} cancelled`} /><MetricCard label="Open reports" value={data.reports} note="Needs review" /><MetricCard label="Support queue" value={data.support} note="Open or in progress" /></div><div className="overview-grid"><section className="panel chart-panel"><div className="section-title"><div><h2>Activity trend</h2><p>Calls and recharges over the recent period</p></div><span className="live-dot">● Live</span></div><DashboardTrend data={data.trend} /></section><section className="panel"><div className="section-title"><div><h2>Latest wallet activity</h2><p>Recent wallet entries for revenue and calls</p></div></div><div className="activity-list">{data.recent.map((row, index) => <div className="activity-row" key={`${row.created_at}-${index}`}><div><strong>{row.metadata?.counterpartyName || row.title || row.kind}</strong><small>{new Date(row.created_at).toLocaleString('en-IN')}</small></div><span className={Number(row.coins_delta) < 0 ? 'amount negative' : 'amount'}>{Number(row.coins_delta) > 0 ? '+' : ''}{row.coins_delta || 0} coins</span><StatusBadge value={row.metadata?.callStatus || row.status} /></div>)}{!data.recent.length && <div className="empty">No recent activity.</div>}</div></section></div></>
}
