import { useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import StatusBadge from './StatusBadge'

export default function RechargeDashboard() {
  const [orders, setOrders] = useState([]); const [users, setUsers] = useState({}); const [query, setQuery] = useState(''); const [selected, setSelected] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const load = useCallback(async () => {
    setLoading(true); const result = await supabase.from('recharge_orders').select('order_id,user_id,coins,amount_rupees,status,created_at,completed_at').order('created_at', { ascending: false }).limit(500)
    if (result.error) { setError(result.error.message); setLoading(false); return }
    const rows = result.data || []; const ids = [...new Set(rows.map(row => row.user_id).filter(Boolean))]; const people = ids.length ? await supabase.from('users').select('id,public_id,username,phone,role,account_status').in('id', ids) : { data: [] }
    setUsers(Object.fromEntries((people.data || []).map(user => [user.id, user]))); setOrders(rows); setError(people.error?.message || ''); setLoading(false)
  }, [])
  useEffect(() => { load() }, [load])
  const completed = orders.filter(row => row.status === 'completed'); const amount = completed.reduce((sum, row) => sum + Number(row.amount_rupees || 0), 0); const visible = useMemo(() => orders.filter(row => JSON.stringify({ ...row, user: users[row.user_id] }).toLowerCase().includes(query.toLowerCase())), [orders, users, query])
  const selectedRows = selected ? orders.filter(row => row.user_id === selected.user_id) : []
  return <><div className="page-actions"><div><p className="eyebrow">Recharges</p><h2 className="page-heading">Recharge users</h2><p className="muted">Review recharge orders, amounts, and user history.</p></div><button className="ghost-btn" onClick={load}>Refresh</button></div>{error && <div className="error">{error}</div>}<div className="metric-grid metric-grid-small"><div className="panel metric"><span>Recharge users</span><strong>{new Set(completed.map(row => row.user_id)).size}</strong><small>Unique completed payers</small></div><div className="panel metric"><span>Completed recharges</span><strong>{completed.length}</strong><small>{orders.length} total attempts</small></div><div className="panel metric"><span>Collected</span><strong>₹{amount.toLocaleString('en-IN')}</strong><small>Completed order value</small></div><div className="panel metric"><span>Coins delivered</span><strong>{completed.reduce((sum, row) => sum + Number(row.coins || 0), 0).toLocaleString()}</strong><small>Across completed orders</small></div></div><div className="panel"><div className="toolbar"><input placeholder="Search by order, user, phone, or status…" value={query} onChange={event => setQuery(event.target.value)} /><span>{visible.length} orders</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Order</th><th>User</th><th>Coins</th><th>Amount</th><th>Status</th><th>Created</th></tr></thead><tbody>{visible.map(row => <tr className="clickable-row" key={row.order_id} onClick={() => setSelected(row)}><td>{row.order_id}</td><td>{users[row.user_id]?.username || users[row.user_id]?.public_id || row.user_id}</td><td>{Number(row.coins).toLocaleString()}</td><td>₹{Number(row.amount_rupees).toLocaleString('en-IN')}</td><td><StatusBadge value={row.status} /></td><td>{new Date(row.created_at).toLocaleString('en-IN')}</td></tr>)}</tbody></table>{loading && <div className="empty">Loading recharge activity…</div>}{!loading && !visible.length && <div className="empty">No matching recharge orders.</div>}</div></div>{selected && <div className="inspector panel"><div className="section-title"><div><h2>User recharge history</h2><p>{users[selected.user_id]?.username || selected.user_id}</p></div><button className="ghost-btn" onClick={() => setSelected(null)}>Close</button></div><div className="mini-log">{selectedRows.map(row => <div key={row.order_id}><span><strong>{row.order_id}</strong><small>{new Date(row.created_at).toLocaleString('en-IN')} · {row.coins} coins</small></span><b>₹{Number(row.amount_rupees).toLocaleString('en-IN')} <StatusBadge value={row.status} /></b></div>)}</div></div>}</>
}
