import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { recordAudit, removeHostStory } from '../lib/adminActions'

const storyId = story => String(story.id || story.storyId || story.mediaUri || story.mediaUrl || '')
export default function StoryModerationPage() {
  const [hosts, setHosts] = useState([]); const [selected, setSelected] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState('')
  const load = useCallback(async () => { const result = await supabase.from('users').select('id,public_id,username,host_status,host_story_items,account_status,host_profile_photo_url').eq('role', 'host').order('created_at', { ascending: false }).limit(300); if (result.error) setError(result.error.message); else setHosts((result.data || []).filter(host => Array.isArray(host.host_story_items) && host.host_story_items.length)) }, [])
  useEffect(() => { load() }, [load])
  const remove = async story => { if (!selected || !window.confirm('Remove this story from the host profile?')) return; const key = `${selected.id}-${storyId(story)}`; setBusy(key); const result = await removeHostStory(selected.id, storyId(story)); if (result.error) setError(result.error.message); else { await recordAudit('host_story_removed', 'user', selected.id, { storyId: storyId(story) }); setSelected({ ...selected, host_story_items: selected.host_story_items.filter(item => storyId(item) !== storyId(story)) }); await load() } setBusy('') }
  return <><div className="page-actions"><div><p className="eyebrow">Stories</p><h2 className="page-heading">Story controls</h2><p className="muted">Review and manage stories published by hosts.</p></div><button className="ghost-btn" onClick={load}>Refresh</button></div>{error && <div className="error">{error}</div>}<div className="story-layout"><div className="panel"><div className="section-title"><div><h2>Hosts with stories</h2><p>{hosts.length} hosts</p></div></div><div className="story-host-list">{hosts.map(host => <button className={`story-host ${selected?.id === host.id ? 'active' : ''}`} key={host.id} onClick={() => setSelected(host)}><div className="avatar">{(host.username || 'H').slice(0, 1).toUpperCase()}</div><span><strong>{host.username || host.public_id}</strong><small>{host.host_story_items.length} stories · {host.host_status || 'unknown'}</small></span></button>)}{!hosts.length && <div className="empty">No active host stories found.</div>}</div></div><div className="panel story-review">{!selected ? <div className="empty">Select a host to review their stories.</div> : <><div className="section-title"><div><h2>{selected.username || selected.public_id}</h2><p>Story list · {selected.host_story_items.length} items</p></div></div><div className="story-grid">{selected.host_story_items.map(story => <article className="story-card" key={storyId(story)}><div className="story-media">{String(story.mediaType || story.type || '').toLowerCase().includes('video') ? <video src={story.mediaUri || story.mediaUrl} controls /> : <img src={story.mediaUri || story.mediaUrl} alt={story.caption || 'Host story'} />}</div><div><strong>{story.caption || 'Untitled story'}</strong><small>{story.createdAt || story.created_at ? new Date(story.createdAt || story.created_at).toLocaleString('en-IN') : 'No timestamp'}</small></div><button className="mini-btn danger-btn" disabled={busy === `${selected.id}-${storyId(story)}`} onClick={() => remove(story)}>{busy === `${selected.id}-${storyId(story)}` ? 'Removing…' : 'Remove story'}</button></article>)}</div></>}</div></div></>
}
