import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import StatusBadge from './StatusBadge'

const statuses = ['open', 'in_progress', 'resolved', 'closed']

export default function SupportInboxPage() {
  const [threads, setThreads] = useState([]); const [users, setUsers] = useState({}); const [selected, setSelected] = useState(null); const [messages, setMessages] = useState([]); const [reply, setReply] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { setLoading(true); const result = await supabase.from('support_threads').select('*').order('updated_at', { ascending: false }).limit(100); if (result.error) { setError(result.error.message); setLoading(false); return } setError(''); setThreads(result.data || []); const ids = (result.data || []).map(row => row.user_id); if (ids.length) { const people = await supabase.from('users').select('id,public_id,username,phone,role').in('id', ids); setUsers(Object.fromEntries((people.data || []).map(user => [user.id, user]))) } setLoading(false) }, [])
  useEffect(() => { load() }, [load])
  useEffect(() => { const timer = window.setInterval(load, 15000); return () => window.clearInterval(timer) }, [load])
  const openThread = async thread => { setSelected(thread); const result = await supabase.from('support_messages').select('*').eq('thread_id', thread.id).order('created_at', { ascending: true }); if (result.error) setError(result.error.message); else setMessages(result.data || []) }
  const updateStatus = async status => { if (!selected) return; const result = await supabase.from('support_threads').update({ status, updated_at: new Date().toISOString() }).eq('id', selected.id); if (result.error) setError(result.error.message); else { await supabase.rpc('admin_record_audit', { p_action: 'support_status_changed', p_entity_type: 'support_thread', p_entity_id: selected.id, p_metadata: { status } }); setSelected({ ...selected, status }); setThreads(items => items.map(item => item.id === selected.id ? { ...item, status } : item)) } }
  const sendReply = async event => { event.preventDefault(); if (!selected || !reply.trim()) return; const user = (await supabase.auth.getUser()).data.user; const result = await supabase.from('support_messages').insert({ thread_id: selected.id, sender_type: 'admin', sender_id: user?.id, body: reply.trim() }).select('*').single(); if (result.error) { setError(result.error.message); return } await supabase.from('support_threads').update({ status: 'in_progress', last_message_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq('id', selected.id); await supabase.rpc('admin_record_audit', { p_action: 'support_reply_sent', p_entity_type: 'support_thread', p_entity_id: selected.id, p_metadata: { messageId: result.data.id } }); setMessages(items => [...items, result.data]); setReply(''); await load() }
  return <div><div className="section-title"><div><h2>Support inbox</h2><p>Review customer requests and support conversations.</p></div><button className="ghost-btn" onClick={load}>Refresh</button></div>{error && <div className="error">{error}</div>}<div className="support-layout"><div className="panel support-list">{loading ? <div className="empty">Loading support threads…</div> : !threads.length ? <div className="empty">No support requests yet.</div> : threads.map(thread => { const user = users[thread.user_id]; return <button className={`support-thread ${selected?.id === thread.id ? 'active' : ''}`} key={thread.id} onClick={() => openThread(thread)}><div><strong>{user?.username || user?.public_id || user?.phone || 'Unknown user'}</strong><small>{thread.subject}</small></div><StatusBadge value={thread.status} /></button> })}</div><div className="panel support-conversation">{!selected ? <div className="empty">Select a request to view the conversation.</div> : <><div className="support-head"><div><h3>{users[selected.user_id]?.username || users[selected.user_id]?.public_id || 'Support request'}</h3><small>{users[selected.user_id]?.phone || selected.user_id}</small></div><select value={selected.status} onChange={event => updateStatus(event.target.value)}>{statuses.map(status => <option key={status} value={status}>{status.replace('_', ' ')}</option>)}</select></div><div className="support-messages">{messages.map(message => <div className={`support-message ${message.sender_type}`} key={message.id}><small>{message.sender_type}</small><p>{message.body}</p><time>{new Date(message.created_at).toLocaleString()}</time></div>)}</div><form className="support-reply" onSubmit={sendReply}><textarea value={reply} onChange={event => setReply(event.target.value)} placeholder="Reply to the user…" /><button className="primary-btn" type="submit">Send reply</button></form></>}</div></div></div>
}
