import { Fragment, useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import StatusBadge from './StatusBadge'
import UserDetailPanel from './UserDetailPanel'

const fields = 'id,public_id,phone,username,gender,role,account_mode,language,native_languages,topic_tags,account_status,host_status,is_online,host_audio_rate,host_video_rate,created_at'
export default function UserManagementPage({ kind, permissions }) {
  const [rows, setRows] = useState([]); const [selected, setSelected] = useState(null); const [query, setQuery] = useState(''); const [error, setError] = useState('')
  const load = useCallback(async () => { const role = kind === 'hosts' ? 'host' : 'user'; const result = await supabase.from('users').select(fields).ilike('role', role).order('created_at', { ascending: false }).limit(100); if (result.error) setError(result.error.message); else { setError(''); setRows(result.data || []) } }, [kind])
  useEffect(() => { load() }, [load])
  const visible = rows.filter(row => JSON.stringify(row).toLowerCase().includes(query.toLowerCase()))
  const save = async event => { event.preventDefault(); const result = await supabase.from('users').update({ username: selected.username, gender: selected.gender, language: selected.language, native_languages: selected.native_languages, topic_tags: selected.topic_tags }).eq('id', selected.id); if (result.error) setError(result.error.message); else { setSelected(null); await load() } }
  const changeStatus = async status => { const label = status === 'banned' ? 'Permanently ban' : status === 'blocked' ? 'Blacklist' : 'Restore access'; if (!window.confirm(`${label} ${selected.username || selected.public_id || selected.id}?`)) return; const result = await supabase.from('users').update({ account_status: status, ban_reason: status === 'active' ? null : `${label} by admin`, banned_at: status === 'active' ? null : new Date().toISOString() }).eq('id', selected.id); if (result.error) setError(result.error.message); else { setSelected(null); await load() } }
  return <><div className="section-title"><div><h2>{kind === 'hosts' ? 'Hosts' : 'Clients'}</h2><p>Only role = {kind === 'hosts' ? 'host' : 'user'} · {visible.length} records</p></div><button className="ghost-btn" onClick={load}>Refresh</button></div>{error && <div className="error">{error}</div>}<div className="panel"><div className="toolbar"><input placeholder={`Search ${kind}…`} value={query} onChange={e => setQuery(e.target.value)} /><span>{visible.length} visible</span></div><div className="table-wrap"><table className="table"><thead><tr><th>User</th><th>Gender</th><th>Phone</th><th>Language</th><th>Status</th><th>Host state</th></tr></thead><tbody>{visible.map(row => <Fragment key={row.id}><tr className="clickable-row" onClick={() => setSelected(selected?.id === row.id ? null : { ...row })}><td>{row.username || row.public_id || row.id?.slice(0, 8) || 'Unknown'}</td><td>{row.gender || 'Not set'}</td><td>{row.phone || 'Not set'}</td><td>{row.language || 'All'}</td><td><StatusBadge value={row.account_status || 'active'} /></td><td>{row.host_status || (kind === 'hosts' ? 'Pending' : 'Not applicable')}</td></tr>{selected?.id === row.id && <tr className="expanded-row"><td colSpan="6"><UserDetailPanel selected={selected} setSelected={setSelected} kind={kind} permissions={permissions} onSave={save} onStatus={changeStatus} error={error} /></td></tr>}</Fragment>)}</tbody></table>{!visible.length && !error && <div className="empty">No {kind} found for this role.</div>}</div></div></>
}
