import { Fragment, useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import StatusBadge from './StatusBadge'
import UserDetailPanel from './UserDetailPanel'
import { recordAudit, setAdminUserStatus } from '../lib/adminActions'

const fields = 'id,public_id,phone,username,gender,role,account_mode,language,native_languages,topic_tags,account_status,host_status,is_online,last_active,wallet_locked,host_audio_rate,host_video_rate,host_profile_photo_url,host_story_items,created_at'
export default function UserManagementPage({ kind, permissions }) {
  const [rows, setRows] = useState([]); const [selected, setSelected] = useState(null); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { setLoading(true); const role = kind === 'hosts' ? 'host' : 'user'; const result = await supabase.from('users').select(fields).eq('role', role).order('created_at', { ascending: false }).limit(500); if (result.error) setError(result.error.message); else { setError(''); setRows(result.data || []) } setLoading(false) }, [kind])
  useEffect(() => { load() }, [load])
  const visible = useMemo(() => rows.filter(row => JSON.stringify(row).toLowerCase().includes(query.toLowerCase())), [rows, query])
  const save = async event => { event.preventDefault(); const values = { username: selected.username, gender: selected.gender, language: selected.language, native_languages: selected.native_languages, topic_tags: selected.topic_tags, wallet_locked: selected.wallet_locked }; if (kind === 'hosts') Object.assign(values, { host_status: selected.host_status, host_audio_rate: selected.host_audio_rate, host_video_rate: selected.host_video_rate }); const result = await supabase.from('users').update(values).eq('id', selected.id); if (result.error) setError(result.error.message); else { await recordAudit('profile_updated', 'user', selected.id, { fields: Object.keys(values) }); setSelected(null); await load() } }
  const changeStatus = async status => { const label = status === 'banned' ? 'Permanently ban' : status === 'blocked' ? 'Block' : status === 'suspended' ? 'Suspend' : 'Restore access'; if (!window.confirm(`${label} ${selected.username || selected.public_id || selected.id}?`)) return; const result = await setAdminUserStatus(selected.id, status, status === 'active' ? '' : `${label} by admin`); if (result.error) setError(result.error.message); else { await recordAudit('user_status_changed', 'user', selected.id, { status }); setSelected(null); await load() } }
  return <><div className="page-actions"><div><p className="eyebrow">Accounts</p><h2 className="page-heading">{kind === 'hosts' ? 'Host management' : 'User management'}</h2><p className="muted">Search accounts and review profile, wallet, and status details.</p></div><button className="ghost-btn" onClick={load}>Refresh</button></div>{error && <div className="error">{error}</div>}<div className="panel"><div className="toolbar"><input placeholder={`Search ${kind} by name, ID, phone, or status…`} value={query} onChange={e => setQuery(e.target.value)} /><span>{visible.length} visible</span></div><div className="table-wrap"><table className="table"><thead><tr><th>User</th><th>Presence</th><th>Language</th><th>Account</th><th>Host state</th><th>Last active</th></tr></thead><tbody>{visible.map(row => <Fragment key={row.id}><tr className="clickable-row" onClick={() => setSelected(selected?.id === row.id ? null : { ...row })}><td><strong>{row.username || row.public_id || row.id?.slice(0, 8) || 'Unknown'}</strong><small className="table-subtitle">ID {row.public_id || '—'} · {row.phone || 'phone hidden'}</small></td><td>{row.is_online ? <span className="presence online">Online</span> : 'Offline'}</td><td>{row.language || 'All'}</td><td><StatusBadge value={row.account_status || 'active'} /></td><td>{row.host_status || (kind === 'hosts' ? 'Pending' : '—')}</td><td>{row.last_active ? new Date(row.last_active).toLocaleString('en-IN') : '—'}</td></tr>{selected?.id === row.id && <tr className="expanded-row"><td colSpan="6"><UserDetailPanel selected={selected} setSelected={setSelected} kind={kind} permissions={permissions} onSave={save} onStatus={changeStatus} error={error} /></td></tr>}</Fragment>)}</tbody></table>{loading && <div className="empty">Loading {kind}…</div>}{!loading && !visible.length && !error && <div className="empty">No {kind} found for this search.</div>}</div></div></>
}
